apiVersion: v1
kind: Service
metadata:
  name: finance-tracker-service
spec:
  selector:
    app: finance-tracker
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort  # Use LoadBalancer for cloud or NodePort for local testing
